"""create resources and allocations

Revision ID: ca29d5588355
Revises: 
Create Date: 2026-02-22 00:19:14.870445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca29d5588355'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('EQUIPMENT', 'VENUE', 'PERSONNEL', 'MATERIAL', name='resourcetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_per_hour', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=False)
    op.create_index(op.f('ix_resources_owner_id'), 'resources', ['owner_id'], unique=False)
    op.create_table('resource_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'MAINTENANCE', name='resourcestatus'), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_allocations_event_id'), 'resource_allocations', ['event_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_id'), 'resource_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_owner_id'), 'resource_allocations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_task_id'), 'resource_allocations', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_allocations_task_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_owner_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_event_id'), table_name='resource_allocations')
    op.drop_table('resource_allocations')
    op.drop_index(op.f('ix_resources_owner_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
