"""test

Revision ID: e2e85b05d150
Revises: f1af177b4e54
Create Date: 2026-04-20 18:32:41.314293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e85b05d150'
down_revision: Union[str, Sequence[str], None] = 'f1af177b4e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ORGANIZER', 'EXECUTOR', 'VIEWER', name='participantrole'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user')
    )
    op.create_index(op.f('ix_event_participants_event_id'), 'event_participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    op.create_index(op.f('ix_event_participants_user_id'), 'event_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_participants_user_id'), table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_event_id'), table_name='event_participants')
    op.drop_table('event_participants')
    # ### end Alembic commands ###
