"""add email to user_profiles

Revision ID: 646b02feb82c
Revises: c1192a639522
Create Date: 2026-03-20 22:59:59.959084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646b02feb82c'
down_revision: Union[str, Sequence[str], None] = 'c1192a639522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###
