upstream auth-service {
    server auth_service:8001;
}

upstream user-service {
    server user_service:8003;
}

upstream event-service {
    server event_service:8002;
}

upstream task-service {
    server task_service:8004;
}

upstream resource-service {
    server resource_service:8005;
}

server {
    listen 80;
    server_name localhost;

    location /health {
        return 200 "API Gateway OK\n";
        add_header Content-Type text/plain;
    }

    location /api/auth/ {
        proxy_pass http://auth-service/api/v1/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/users/ {
        proxy_pass http://user-service/api/v1/users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/events/ {
        proxy_pass http://event-service/api/v1/events/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

        location /api/tasks/ {
        proxy_pass http://task-service/api/v1/tasks/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

        location /api/resources/ {
        proxy_pass http://resource-service/api/v1/resources/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 404 "API endpoints:\n/health\n/api/auth/\n/api/users/\n/api/events/\n/api/tasks/\n/api/resources/\n";
    }
}
