"""add task history and actual time

Revision ID: 7254c0f2b33e
Revises: 87fd4092a856
Create Date: 2026-04-10 15:37:19.075949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7254c0f2b33e'
down_revision: Union[str, Sequence[str], None] = '87fd4092a856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'actual_end_time')
    op.drop_column('tasks', 'actual_start_time')
    # ### end Alembic commands ###
