"""add_history

Revision ID: 87fd4092a856
Revises: b91f8ce1cf01
Create Date: 2026-04-08 10:32:31.548998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87fd4092a856'
down_revision: Union[str, Sequence[str], None] = 'b91f8ce1cf01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'start_time')
    # ### end Alembic commands ###
